name: Artifact

on: [push]

env: 
  ARTIFACT_NAME: myartifact

jobs:
  main:
    runs-on: ubuntu-latest
    steps: 
    - name: Check out
      use: actions/checkout@v2
    - name: Upload
      use: actions/upload-artifact@v2
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: .
